A = [7,4,2;3,5,6;-1,2,1];
B = [1,0,1;2,3,4;-1,6,7];
disp('A+B is : ');
disp(A+B);
disp('AB is : ');
disp(A*B);
disp('A^2 is : ');
disp(A^2);
disp('AT is :');
disp(A');
disp('B-1 is : ');
disp(B-1);
disp('BTAT is : ');
disp(B'*A');
disp('A^2 + B^2 - A*B is :');
disp(A^2 + B^2 - A*B);
disp('|A| is : ');
disp(abs(A));
disp('|B| is : ');
disp(abs(B));
disp('|AB| is : ');
disp(abs(A*B));
